### PR TITLE
Added License,Badge Replaced in README.md

### PR DESCRIPTION
**Pull request by SubhradeepSS**

### CODE REVIEW

**Review by piyushchauhan — APPROVED** [review]
Good Work

**Comment by piyushchauhan** [comment]
Closes #5 #3

**Comment by SubhradeepSS** [comment]
@piyushchauhan was any score allotted for the license and badge issue?
My score was not incremented for the specified issue.
Can u please check it out?

**Comment by piyushchauhan** [comment]
> @piyushchauhan was any score allotted for the license and badge issue?
> My score was not incremented for the specified issue.
> Can u please check it out?

Update made.

**Pull request merged**
